import os

file_path = r'c:\Users\ADMIN\Desktop\Aarogya Sathi\docs\Aarogya_Sathi_Presentation_Preview.html'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Fix interactivity
content = content.replace('interactivity:inert;', '')
content = content.replace('interactivity:auto;', '')

# 2. Fix color-adjust
content = content.replace('color-adjust:exact!important;', 'print-color-adjust:exact!important;')

# 3. Fix background-clip
content = content.replace('-webkit-background-clip:text;', '-webkit-background-clip:text;background-clip:text;')

# 4. Fix colon expected inside inline styles generated by Marp
# Looking at the pattern:
# style=\"--paginate...;\" data-...
# We can just remove the newline character before the closing quote and semicolon
# Because the IDE parses `style=\"--header: ... \n;\"` and throws colon expected since there's no prop before `:`
content = content.replace('\\n;\" data-marpit-pagination-total', ';\" data-marpit-pagination-total')
# Also, escaping strings for custom variables
lines = content.split('\\n')
for i, line in enumerate(lines):
    if 'style=\"--paginate:true;' in line:
        # Simplest fix to silence the IDE checker: just replace the inline style tag entirely or quote values.
        # But actually, the IDE is complaining about `colon expected` at lines 108, 224, etc.
        # Line 108 is `;" data-marpit-pagination-total="14" data-size="16:9">`
        # Because the previous line ends with a property without quotes maybe?
        # The true problem is `--style:@import url(...)` which contains unescaped stuff, 
        # or just the raw newline inside the style attribute is breaking it.
        pass

# Let's just strip the problematic custom properties: --header, --footer, --class, --theme, --style
# since this is just a preview HTML
import re
content = re.sub(r'--header:[^;]+;', '', content)
content = re.sub(r'--footer:[^;]+;', '', content)
content = re.sub(r'--class:[^;]+;', '', content)
content = re.sub(r'--theme:[^;]+;', '', content)
content = re.sub(r'--style:[^\"]+', '', content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print(\"Patched successfully.\")
